name: website cd

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: website/

jobs:
  cd:
    name: Build and deploy website
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 20.12.2
        package-manager:
          - yarn
        lockfile:
          - website/yarn.lock

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.package-manager }}
          cache-dependency-path: ${{ matrix.lockfile }}

      - name: Install dependencies
        run: yarn

      - name: Lint project
        run: yarn lint

      - name: Generate project
        run: yarn generate

      - name: Deploy project to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: website/.output/public
